import type { PricingPlan } from "@/components/pricing/types";

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    tagline: "Try the platform on capped usage",
    priceLabel: "$0",
    priceHint: "No card required",
    features: [
      "Starter session and token caps",
      "Core AI employees and dashboard",
      "Best for evaluation and demos",
    ],
    ctaLabel: "Start free",
    ctaVariant: "outline",
    href: "/sign-up",
  },
  {
    id: "pro",
    name: "Pro",
    tagline: "For teams shipping real volume",
    badge: "Recommended",
    priceLabel: "$66/mo",
    priceHint: "Per workspace · billed monthly",
    yearlyPriceLabel: "$660/yr",
    yearlyPriceHint: "~$55/mo effective · per workspace · billed annually",
    features: [
      "Higher session and token limits",
      "Realtime sessions and voice",
      "Faster routing and priority capacity",
      "Checkout with Polar from Pricing or Settings",
    ],
    ctaLabel: "Upgrade to Pro",
    ctaVariant: "default",
    href: "/premium",
    highlighted: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    tagline: "Contract, security, and scale",
    priceLabel: "Custom",
    priceHint: "Annual agreements",
    features: [
      "Usage aligned to your contract",
      "Dedicated or isolated infrastructure options",
      "SLA-backed support",
      "SSO, integrations, and procurement-friendly terms",
    ],
    ctaLabel: "Contact sales",
    ctaVariant: "outline",
    href: "mailto:sales@nullxes.com?subject=Enterprise%20plan",
  },
  {
    id: "govtech",
    name: "GovTech",
    tagline: "Regulated and high-assurance environments",
    priceLabel: "Custom",
    priceHint: "Compliance-led onboarding",
    features: [
      "Deployment patterns for sensitive data",
      "On-prem or sovereign-friendly options",
      "Documentation for audit and compliance reviews",
      "Named technical and success contacts",
    ],
    ctaLabel: "Request access",
    ctaVariant: "outline",
    href: "mailto:sales@nullxes.com?subject=GovTech%20plan",
  },
];
