import type { PricingPlan } from "@/components/pricing/types";

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    tagline: "Enter the system. Test the workforce.",
    priceLabel: "$0",
    priceHint: "No card · instant access",
    features: [
      "Limited runtime for AI employees",
      "Access to core dashboard and flows",
      "Basic sessions for testing scenarios",
      "Built for exploration and prototyping",
    ],
    ctaLabel: "Enter NULLXES",
    ctaVariant: "outline",
    href: "/sign-up",
  },
  {
    id: "pro",
    name: "Pro",
    tagline: "Deploy digital employees in production",
    badge: "Most chosen",
    priceLabel: "$66/mo",
    priceHint: "Per workspace · scalable usage",
    yearlyPriceLabel: "$660/yr",
    yearlyPriceHint: "~$55/mo effective · optimized for teams",
    features: [
      "Expanded session and token throughput",
      "Realtime execution (voice + avatar)",
      "Priority compute and routing layer",
      "Stable performance under load",
      "Integrated billing via Polar",
    ],
    ctaLabel: "Activate Pro",
    ctaSubtext: "Secure checkout via Polar · manage or cancel anytime",
    ctaVariant: "default",
    href: "/premium",
    highlighted: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    tagline: "Infrastructure aligned to your organization",
    priceLabel: "Custom",
    priceHint: "Contract-based deployment",
    features: [
      "Custom throughput and scaling policies",
      "Dedicated or isolated runtime environments",
      "SLA-backed uptime and support",
      "SSO, internal integrations, enterprise workflows",
      "Procurement-ready contracts and onboarding",
    ],
    ctaLabel: "Contact engineering",
    ctaVariant: "outline",
    href: "mailto:devpos@nullxes.com?subject=Enterprise%20NULLXES",
  },
  {
    id: "govtech",
    name: "GovTech",
    tagline: "Built for regulated and sovereign systems",
    priceLabel: "Custom",
    priceHint: "Compliance-first onboarding",
    features: [
      "Sovereign and on-prem deployment models",
      "Secure handling of sensitive workloads",
      "Audit-ready documentation and architecture",
      "Dedicated technical and compliance contacts",
      "Long-term infrastructure partnerships",
    ],
    ctaLabel: "Request access",
    ctaVariant: "outline",
    href: "mailto:devpos@nullxes.com?subject=GovTech%20NULLXES",
  },
];